name: Deploy Backend (PM2 - sin Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS Backend (PM2)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_BACKEND_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/gb-constructora-backend
            git pull origin main
            chmod +x deploy_pm2.sh
            ./deploy_pm2.sh
