name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS Backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_BACKEND_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/gb-constructora-backend
            git pull origin main
            docker-compose down
            docker-compose up -d --build --force-recreate
            docker image prune -af
            docker builder prune -af --filter "until=24h"
